# Generated by Django 4.1.7 on 2024-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal', models.CharField(default='Hubli', max_length=400)),
                ('year', models.CharField(default='Hubli', max_length=400)),
                ('price', models.CharField(default='Hubli', max_length=400)),
                ('Engine', models.CharField(default='Hubli', max_length=400)),
                ('Mileage', models.CharField(default='Hubli', max_length=400)),
                ('about_car', models.CharField(default='Hubli', max_length=400)),
                ('car_img1', models.FileField(upload_to='upload_img/')),
                ('car_img2', models.FileField(upload_to='upload_img/')),
                ('car_img3', models.FileField(upload_to='upload_img/')),
            ],
        ),
    ]
