# Generated by Django 4.1.7 on 2024-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cardetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Hubli', max_length=400)),
                ('email', models.CharField(default='Hubli', max_length=400)),
                ('phone_no', models.CharField(default='Hubli', max_length=400)),
                ('address', models.CharField(default='Hubli', max_length=400)),
            ],
        ),
    ]
