# Generated by Django 4.1.7 on 2024-04-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_carorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarOrders',
        ),
    ]
