# Generated by Django 4.1.7 on 2024-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_carorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Hubli', max_length=400)),
                ('email', models.CharField(default='Hubli', max_length=400)),
                ('phone_no', models.CharField(default='Hubli', max_length=400)),
                ('msg', models.CharField(default='Hubli', max_length=400)),
            ],
        ),
    ]
